package com.cinema.selenium;

import com.cinema.util.DBUtils;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.Duration;

import org.junit.After;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.edge.EdgeDriver;
import org.openqa.selenium.edge.EdgeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import static org.junit.Assert.assertTrue;

/**
 * Selenium WebDriver end-to-end test for UC55: View Notifications.
 * Notifications are currently only generated by the Shift Exchange feature
 * (UC54), so this test seeds Notification rows directly rather than driving
 * a full exchange, then exercises the bell icon's unread badge and
 * "mark all as read" action (BR-45.1: scoped to the owning account).
 *
 * Requires the app running at BASE_URL (deployed via NetBeans/Tomcat) and a
 * reachable SQL Server database. Browser: Microsoft Edge (Chromium).
 */
public class NotificationMarkAsReadSeleniumTest {

    private static final String BASE_URL = "http://localhost:8088/MoviesTheater";
    private static final String EMPLOYEE_EMAIL = "employee@cinema.vn";
    private static final int EMPLOYEE_ACCOUNT_ID = 3; // employee@cinema.vn
    private static final String PASSWORD = "123456";

    private WebDriver driver;

    private WebDriver newDriver() {
        EdgeOptions options = new EdgeOptions();
        options.addArguments("--remote-allow-origins=*");
        options.addArguments("--user-data-dir=" + System.getProperty("java.io.tmpdir")
                + "selenium-edge-profile-" + System.nanoTime());
        return new EdgeDriver(options);
    }

    @After
    public void tearDown() {
        if (driver != null) driver.quit();
    }

    private void login(WebDriver driver, String email, String password) {
        driver.get(BASE_URL + "/Login");
        driver.findElement(By.id("email")).sendKeys(email);
        driver.findElement(By.id("password")).sendKeys(password);
        driver.findElement(By.cssSelector("#loginForm button[type=submit]")).click();
        new WebDriverWait(driver, Duration.ofSeconds(10))
                .until(ExpectedConditions.urlContains("/employee"));
    }

    private WebDriverWait wait(WebDriver driver) {
        return new WebDriverWait(driver, Duration.ofSeconds(10));
    }

    private void seedUnreadNotification(String title) throws SQLException {
        String sql = "INSERT INTO Notification (AccountID, Type, Title, Message, IsRead) "
                + "VALUES (?, 'SHIFT_EXCHANGE_REQUESTED', ?, N'Selenium seeded notification', 0)";
        try (Connection conn = DBUtils.getConnection();
                PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setInt(1, EMPLOYEE_ACCOUNT_ID);
            ps.setNString(2, title);
            ps.executeUpdate();
        }
    }

    @Test
    public void testMarkAllAsRead_clearsUnreadBadge() throws SQLException {
        seedUnreadNotification("Selenium notif A " + System.nanoTime());
        seedUnreadNotification("Selenium notif B " + System.nanoTime());

        driver = newDriver();
        login(driver, EMPLOYEE_EMAIL, PASSWORD);
        driver.get(BASE_URL + "/employee/schedules");

        driver.findElement(By.id("cgvNotifBellBtn")).click();

        WebElement badge = wait(driver).until(
                ExpectedConditions.visibilityOfElementLocated(By.id("cgvNotifBadge")));
        assertTrue(Integer.parseInt(badge.getText().replace("+", "")) >= 2);

        wait(driver).until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector(".cgv-notif-item")));
        driver.findElement(By.id("cgvNotifMarkAll")).click();

        wait(driver).until(ExpectedConditions.invisibilityOfElementLocated(By.id("cgvNotifBadge")));
    }
}
