USE master;
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = N'CinemaBookingDB')
    DROP DATABASE CinemaBookingDB;
GO

CREATE DATABASE CinemaBookingDB;
GO

USE CinemaBookingDB;
GO

CREATE TABLE [Role] (
	[RoleID] INT IDENTITY(1,1),
	[RoleName] NVARCHAR(50) NOT NULL UNIQUE,
	PRIMARY KEY([RoleID])
);

CREATE TABLE [Account] (
	[AccountID] INT IDENTITY(1,1),
	[Email] VARCHAR(255) NOT NULL UNIQUE,
	[Password] VARCHAR(255) NOT NULL,
	[RoleID] INT NOT NULL,
	[IsBlocked] BIT NOT NULL DEFAULT 0,
	[AccountStatus] VARCHAR(20) NOT NULL DEFAULT 'noneed',
	[CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
	[ResetToken] VARCHAR(255) NOT NULL,
	[ResetTokenExpiry] DATETIME NOT NULL,
	PRIMARY KEY([AccountID])
);

CREATE TABLE [UserProfile] (
	[AccountID] INT,
	[FullName] NVARCHAR(100) NOT NULL,
	[PhoneNumber] VARCHAR(20) NOT NULL,
	[DoB] DATE NOT NULL,
	[Address] NVARCHAR(255) NOT NULL,
	[AvatarURL] VARCHAR(500) NOT NULL,
	PRIMARY KEY([AccountID])
);

CREATE TABLE [Movie] (
	[MovieID] INT IDENTITY(1,1),
	[MovieName] NVARCHAR(255) NOT NULL,
	[Description] NVARCHAR(MAX) NOT NULL,
	[Duration] INT NOT NULL,
	[ReleaseDate] DATE NOT NULL,
	[Poster] VARCHAR(500) NOT NULL,
	[Trailer] VARCHAR(500) NOT NULL,
	[Language] NVARCHAR(50) NOT NULL,
	[Subtitle] NVARCHAR(50) NOT NULL,
	[Director] NVARCHAR(100) NOT NULL,
	[Cast] NVARCHAR(500) NOT NULL,
	[Country] NVARCHAR(100) NOT NULL,
	[AgeRestriction] INT NOT NULL DEFAULT 0,
	[IsActive] BIT NOT NULL DEFAULT 1,
	[DateAdded] DATETIME NOT NULL,
	[Budget] VARCHAR(50) NOT NULL,
	[GlobalBoxOffice] VARCHAR(50) NOT NULL,
	[WeeklyRevenueRank] INT NOT NULL DEFAULT 0,
	[TicketsSoldMilestone] INT NOT NULL DEFAULT 0,
	PRIMARY KEY([MovieID])
);

CREATE TABLE [Genre] (
	[GenreID] INT IDENTITY(1,1),
	[GenreName] NVARCHAR(100) NOT NULL UNIQUE,
	PRIMARY KEY([GenreID])
);

CREATE TABLE [MovieGenre] (
	[MovieID] INT NOT NULL,
	[GenreID] INT NOT NULL,
	PRIMARY KEY([MovieID], [GenreID])
);

CREATE TABLE [Room] (
	[RoomID] INT IDENTITY(1,1),
	[RoomNumber] VARCHAR(50) NOT NULL UNIQUE,
	[RoomType] VARCHAR(20) NOT NULL DEFAULT '2D',
	[Capacity] INT NOT NULL,
	[NumberOfRows] INT NOT NULL DEFAULT 5,
	[SeatsPerRow] INT NOT NULL DEFAULT 10,
	[IsActive] BIT NOT NULL DEFAULT 1,
	PRIMARY KEY([RoomID])
);

CREATE TABLE [Seat] (
	[SeatID] INT IDENTITY(1,1),
	[RoomID] INT NOT NULL,
	[RowChar] VARCHAR(5) NOT NULL,
	[ColNumber] INT NOT NULL,
	[SeatType] VARCHAR(20) NOT NULL DEFAULT 'Normal',
	[IsActive] BIT NOT NULL DEFAULT 1,
	PRIMARY KEY([SeatID])
);

CREATE TABLE [Schedule] (
	[ScheduleID] INT IDENTITY(1,1),
	[RoomID] INT NOT NULL,
	[MovieID] INT NOT NULL,
	[StartTime] DATETIME NOT NULL,
	[EndTime] DATETIME NOT NULL,
	[BaseTicketPrice] DECIMAL(10,2) NOT NULL,
	[Status] VARCHAR(20) NOT NULL DEFAULT 'Scheduled',
	PRIMARY KEY([ScheduleID])
);

CREATE TABLE [Food] (
	[FoodID] INT IDENTITY(1,1),
	[FoodName] NVARCHAR(100) NOT NULL,
	[Price] DECIMAL(10,2) NOT NULL,
	[Image] VARCHAR(500) NOT NULL,
	[IsActive] BIT NOT NULL DEFAULT 1,
	[IsCombo] BIT NOT NULL DEFAULT 0,
	PRIMARY KEY([FoodID])
);

CREATE TABLE [Promotion] (
	[PromotionID] INT IDENTITY(1,1),
	[PromotionCode] VARCHAR(50) NOT NULL UNIQUE,
	[Description] NVARCHAR(255) NOT NULL,
	[DiscountType] VARCHAR(20) NOT NULL,
	[DiscountValue] DECIMAL(10,2) NOT NULL,
	[MinOrderAmount] DECIMAL(10,2) NOT NULL DEFAULT 0,
	[MaxDiscountAmount] DECIMAL(10,2) NOT NULL,
	[StartDate] DATETIME NOT NULL,
	[EndDate] DATETIME NOT NULL,
	[UsageLimit] INT NOT NULL,
	[UsedCount] INT NOT NULL DEFAULT 0,
	[IsActive] BIT NOT NULL DEFAULT 1,
	[Status] VARCHAR(20) NOT NULL DEFAULT 'active',
	PRIMARY KEY([PromotionID])
);

CREATE TABLE [Invoice] (
	[InvoiceID] INT IDENTITY(1,1),
	[AccountID] INT NOT NULL,
	[PromotionID] INT NOT NULL,
	[SubTotal] DECIMAL(10,2) NOT NULL,
	[DiscountAmount] DECIMAL(10,2) NOT NULL DEFAULT 0,
	[TotalAmount] DECIMAL(10,2) NOT NULL,
	[PaymentMethod] VARCHAR(50) NOT NULL,
	[PaymentStatus] VARCHAR(20) NOT NULL DEFAULT 'Pending',
	[CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
	PRIMARY KEY([InvoiceID])
);

CREATE TABLE [Ticket] (
	[TicketID] INT IDENTITY(1,1),
	[ScheduleID] INT NOT NULL,
	[SeatID] INT NOT NULL,
	[InvoiceID] INT NOT NULL,
	[PriceAtBooking] DECIMAL(10,2) NOT NULL,
	[Code] VARCHAR(100) NOT NULL UNIQUE,
	[IsCheckedIn] BIT NOT NULL DEFAULT 0,
	[CheckedInAt] DATETIME NOT NULL,
	PRIMARY KEY([TicketID])
);

CREATE TABLE [InvoiceFood] (
	[InvoiceID] INT NOT NULL,
	[FoodID] INT NOT NULL,
	[Quantity] INT NOT NULL DEFAULT 1,
	[PriceAtBooking] DECIMAL(10,2) NOT NULL,
	PRIMARY KEY([InvoiceID], [FoodID])
);

CREATE TABLE [MovieReview] (
	[ReviewID] INT IDENTITY(1,1),
	[MovieID] INT NOT NULL,
	[AccountID] INT NOT NULL,
	[TicketID] INT NOT NULL UNIQUE,
	[RatingValue] INT NOT NULL,
	[Comment] NVARCHAR(MAX) NOT NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
	PRIMARY KEY([ReviewID])
);

CREATE TABLE [WorkShift] (
	[ShiftID] INT IDENTITY(1,1),
	[EmployeeID] INT NOT NULL,
	[ShiftDate] DATE NOT NULL,
	[StartTime] TIME NOT NULL,
	[EndTime] TIME NOT NULL,
	[Status] VARCHAR(20) NOT NULL DEFAULT 'Scheduled',
	[Notes] NVARCHAR(500) NOT NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
	PRIMARY KEY([ShiftID])
);

CREATE TABLE [ShiftExchangeRequest] (
	[RequestID] INT IDENTITY(1,1),
	[ShiftID] INT NOT NULL,
	[RequesterID] INT NOT NULL,
	[TargetEmpID] INT NOT NULL,
	[Message] NVARCHAR(500) NOT NULL,
	[Status] VARCHAR(20) NOT NULL DEFAULT 'Pending',
	[CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
	[RespondedAt] DATETIME NOT NULL,
	PRIMARY KEY([RequestID])
);

CREATE TABLE [SystemLog] (
	[LogID] INT IDENTITY(1,1),
	[AccountID] INT NOT NULL,
	[ActionType] VARCHAR(100) NOT NULL,
	[Description] NVARCHAR(MAX) NOT NULL,
	[IPAddress] VARCHAR(45) NOT NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
	PRIMARY KEY([LogID])
);

CREATE TABLE [Notification] (
	[NotificationID] INT IDENTITY(1,1),
	[AccountID] INT NOT NULL,
	[Type] VARCHAR(50) NOT NULL,
	[Title] NVARCHAR(200) NOT NULL,
	[Message] NVARCHAR(500) NOT NULL,
	[ReferenceID] INT NOT NULL,
	[IsRead] BIT NOT NULL DEFAULT 0,
	[CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
	PRIMARY KEY([NotificationID])
);

CREATE TABLE [SystemConfig] (
	[ConfigKey] VARCHAR(100) NOT NULL,
	[ConfigValue] NVARCHAR(MAX) NOT NULL,
	[Description] NVARCHAR(255) NOT NULL,
	[UpdatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
	[UpdatedBy] INT NOT NULL,
	PRIMARY KEY([ConfigKey])
);

CREATE TABLE [UnlockRequest] (
	[RequestID] INT IDENTITY(1,1),
	[AccountID] INT NOT NULL,
	[Reason] NVARCHAR(MAX) NOT NULL,
	[Status] VARCHAR(20) NOT NULL DEFAULT 'Pending',
	[ReviewedBy] INT NOT NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
	[ReviewedAt] DATETIME NOT NULL,
	PRIMARY KEY([RequestID])
);

CREATE TABLE [DeletionRequest] (
	[RequestID] INT IDENTITY(1,1),
	[AccountID] INT NOT NULL,
	[Reason] NVARCHAR(MAX) NOT NULL,
	[Status] VARCHAR(20) NOT NULL DEFAULT 'Pending',
	[ReviewedBy] INT NOT NULL,
	[CreatedAt] DATETIME NOT NULL DEFAULT GETDATE(),
	[ReviewedAt] DATETIME NOT NULL,
	PRIMARY KEY([RequestID])
);

ALTER TABLE [Account] ADD FOREIGN KEY([RoleID]) REFERENCES [Role]([RoleID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [UserProfile] ADD FOREIGN KEY([AccountID]) REFERENCES [Account]([AccountID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [MovieGenre] ADD FOREIGN KEY([MovieID]) REFERENCES [Movie]([MovieID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [MovieGenre] ADD FOREIGN KEY([GenreID]) REFERENCES [Genre]([GenreID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [Seat] ADD FOREIGN KEY([RoomID]) REFERENCES [Room]([RoomID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [Schedule] ADD FOREIGN KEY([RoomID]) REFERENCES [Room]([RoomID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [Schedule] ADD FOREIGN KEY([MovieID]) REFERENCES [Movie]([MovieID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [Invoice] ADD FOREIGN KEY([AccountID]) REFERENCES [Account]([AccountID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [Invoice] ADD FOREIGN KEY([PromotionID]) REFERENCES [Promotion]([PromotionID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [Ticket] ADD FOREIGN KEY([ScheduleID]) REFERENCES [Schedule]([ScheduleID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [Ticket] ADD FOREIGN KEY([SeatID]) REFERENCES [Seat]([SeatID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [Ticket] ADD FOREIGN KEY([InvoiceID]) REFERENCES [Invoice]([InvoiceID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [InvoiceFood] ADD FOREIGN KEY([InvoiceID]) REFERENCES [Invoice]([InvoiceID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [InvoiceFood] ADD FOREIGN KEY([FoodID]) REFERENCES [Food]([FoodID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [MovieReview] ADD FOREIGN KEY([MovieID]) REFERENCES [Movie]([MovieID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [MovieReview] ADD FOREIGN KEY([AccountID]) REFERENCES [Account]([AccountID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [MovieReview] ADD FOREIGN KEY([TicketID]) REFERENCES [Ticket]([TicketID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [WorkShift] ADD FOREIGN KEY([EmployeeID]) REFERENCES [Account]([AccountID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [ShiftExchangeRequest] ADD FOREIGN KEY([ShiftID]) REFERENCES [WorkShift]([ShiftID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [ShiftExchangeRequest] ADD FOREIGN KEY([RequesterID]) REFERENCES [Account]([AccountID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [ShiftExchangeRequest] ADD FOREIGN KEY([TargetEmpID]) REFERENCES [Account]([AccountID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [SystemLog] ADD FOREIGN KEY([AccountID]) REFERENCES [Account]([AccountID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [Notification] ADD FOREIGN KEY([AccountID]) REFERENCES [Account]([AccountID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [SystemConfig] ADD FOREIGN KEY([UpdatedBy]) REFERENCES [Account]([AccountID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [UnlockRequest] ADD FOREIGN KEY([AccountID]) REFERENCES [Account]([AccountID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [UnlockRequest] ADD FOREIGN KEY([ReviewedBy]) REFERENCES [Account]([AccountID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [DeletionRequest] ADD FOREIGN KEY([AccountID]) REFERENCES [Account]([AccountID]) ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE [DeletionRequest] ADD FOREIGN KEY([ReviewedBy]) REFERENCES [Account]([AccountID]) ON UPDATE NO ACTION ON DELETE NO ACTION;