-- Thêm Couple vào Seat CHECK constraint
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS WHERE CONSTRAINT_NAME='CHK_Seat_Type')
    ALTER TABLE Seat DROP CONSTRAINT CHK_Seat_Type;
GO
ALTER TABLE Seat ADD CONSTRAINT CHK_Seat_Type CHECK (SeatType IN ('Normal', 'VIP', 'Couple'));
GO

-- Thêm cột NumberOfRows, SeatsPerRow (nếu chưa có)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Room' AND COLUMN_NAME='NumberOfRows')
    ALTER TABLE Room ADD NumberOfRows INT NOT NULL DEFAULT 0;
GO
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Room' AND COLUMN_NAME='SeatsPerRow')
    ALTER TABLE Room ADD SeatsPerRow INT NOT NULL DEFAULT 0;
GO

-- Thêm IsActive vào Seat (nếu chưa có)
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='Seat' AND COLUMN_NAME='IsActive')
    ALTER TABLE Seat ADD IsActive BIT NOT NULL DEFAULT 1;
GO
